## Productivity

```{r}
myload(temporal_network_metrics, dir = mypath("data", "classes"))
temporal_network_metrics_classes <- temporal_network_metrics
myload(temporal_network_metrics, dir = dest_dir)
myload(community_metrics, dir = data_common)
myload(temporal_community_metrics, synchrony, dir = data_common)
```

```{r prod-dist, fig.cap = "Median community biomass by station"}
biomass_prod_station <- temporal_community_metrics %>%
  select(station, biomass_med, bm_std_med, richness_med, rich_std_med) %>%
  rename(biomass = biomass_med)

plot_biomass_dist <- ggplot(biomass_prod_station, aes(x = biomass)) +
  geom_histogram() +
  labs(
    x = "Median of biomass (g)",
    y = "# of stations"
  )
plot_biomass_dist

plot_biomass_std_dist <- ggplot(biomass_prod_station, aes(x = bm_std_med)) +
  geom_histogram() +
  labs(
    x = "Median of standardized biomass (g/m2)",
    y = "# of stations"
  )
plot_biomass_std_dist
```

There is no bistability in biomass distribution.

```{r prod-net, fig.cap = "Median biomass versus their median network metrics by station."}
avg_network <- temporal_network_metrics %>%
  select_at(vars(dplyr::matches("med|station")))
#colnames(temporal_network_metrics)
biomass_prod_station <- temporal_community_metrics %>%
  select(station, biomass_med, richness_med) %>%
  rename(biomass = biomass_med)
prod_biomass_net_avg <- left_join(avg_network, biomass_prod_station) %>%
  gather(metrics, values, colnames(select_at(., vars((dplyr::matches("med")))))) %>%
  mutate(metrics = str_replace(metrics, "_med", "")) %>%
  filter(metrics != "nbnode")

net_troph_group <- temporal_network_metrics_classes %>% 
  select(station, troph_group) %>%
  unnest() %>%
  filter(!is.na(troph_group)) %>%
  mutate(troph_group = as.factor(troph_group))
# TODO: think about not facetting (list of plots ?)
# Facet label:
formula <- y ~ x #needed for stat_poly_eq
plot_stab_biomass_net_avg <- ggplot(prod_biomass_net_avg, aes(y = biomass, x = values)) +
  geom_point() +
  facet_wrap(~metrics, labeller = mylabel(), scales = "free_x") +
  geom_smooth(method = 'lm') +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(
    x = "Median of the network indices",
    y = "Average Biomass"
  )
plot_stab_biomass_net_avg
```

### Biomass richness

```{r}
# Raw biomass
raw_bm_rich <- biomass_prod_station %>% 
  select(station, biomass, richness_med) %>%
  rename(richness = richness_med) %>%
  mutate(type = "raw")
std_bm_rich <- biomass_prod_station %>% 
  select(station, bm_std_med, rich_std_med) %>%
  rename(richness = rich_std_med, biomass = bm_std_med) %>%
  mutate(type = "std")

p_bm_rich_raw_std <- map(list(raw_bm_rich, std_bm_rich), function (x) {

  if (unique(x$type) == "raw") {
    x_lab <- paste0("Median richness")
    y_lab <- paste0("Median biomass (g)")
  } else {
    x_lab <- paste0("Median standardized richness (m2^-1)")
    y_lab <- paste0("Median standardized biomass (g/m2)")
  }

  x %>%
  ggplot(aes(x = log10(richness), y = log10(biomass))) +
  geom_point() +
  labs(x = x_lab, y = y_lab)
  })
plot_grid(plotlist = p_bm_rich_raw_std)
```



### By trophic level 

```{r, fig.cap="Biomass production and stability by trophic level", fig.dim = c(10, 7)}
plot_prod_richness_troph_group <-
  ggplot(net_troph_group, aes(y = biomass_avg, x = richness_avg)) +
  geom_point() +
  facet_grid(cols = vars(troph_group)) +
  geom_smooth(method = 'lm')+
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  xylabs(
    x = "richness_avg",
    y = "biomass_avg"
  )
plot_prod_richness_troph_group
```
