##  Biomass temporal dynamics


```{r load dataset, include = FALSE}
library(jmotif)
myload(community_metrics, op_analysis, dir = mypath("data"))
community_metrics %<>% left_join(select(op_analysis, opcod, station, date))
```

```{r}
ts_biomass  <- community_metrics %>%
  select(station, date, biomass) %>%
  mutate(station = as.character(station)) %>%
  group_by(station) %>%
  arrange(date) %>%
  nest()

ts_biomass %<>%
  mutate(
    zts = map(data, function(x) znorm(x$biomass, threshold = 0.01)),
    paa = map(zts, ~paa(., 3)),
    sax = map_chr(paa, ~series_to_string(., 3))
  )
```

```{r}
pattern_dist <- ts_biomass %>%
  group_by(sax) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
ggplot(ts_biomass, aes(x = sax)) +
  geom_histogram(stat = "count")

filter(pattern_dist, count > 10)
```

```{r}
test <- ts_biomass %>%
  filter(sax %in% c("cba", "bbb", "cab", "abc", "acb", "bca", "bac", "cbb")) %>%
  group_by(sax) %>%
  sample_n(10) %>%
  mutate(
    paa2 = map2(data, zts, function (x, zts) {
      cbind(x[,1], zts)
  }),
    id_sta = as.character(seq(1,n()))

  ) %>%
  unnest(paa2)

ggplot(test, aes(x = date, y = zts)) +
  geom_line(aes(color = id_sta)) +
  facet_wrap(~ sax)

```

```{r}
myload(polluant_units, dir = mypath("data-raw", "polluants", "naiades_data"))

myload(press_metrics, dir = mypath("data"))
press_year <- press_metrics %>%
  filter(category %in% c("fungicides", "herbicides", "insecticides", "DBO", "temperature"))

biomass <- community_metrics %>%
  mutate(
    year = lubridate::year(date),
    category = "biomass",
    press = biomass 
    ) %>%
  select(station, year, category, press)
press_biomass <- press_year %>%
  bind_rows(rename(biomass, id = station)) %>%
  na.omit()
```

```{r}
samp_station <- sample(unique(press_biomass$id), 10)
temp <- press_biomass %>%
  mutate(id = as.character(id)) %>%
  filter(id %in% samp_station)

ggplot(temp, aes(y = press, x = year)) +
  facet_wrap(~category, scales = "free_y") +
  geom_line(aes(color = id))

```
