---
title: "Introduction - Description of the project"
author: "Alain Danet"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: references.bib
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Post-doc objectives

According to the postdoc advertisement:

1. Characterize the temporal stability of the studied communities
2. Disentangle the drivers of stability and to understand how trophic and
   community structures influence stability

## Priority

1. Obtain networks and indicators DONE!
2. Perturbation identification
3. Pulses identification (ex. extreme summer of 2003) 
3. Traits and phylogeny
   - See `fish_trait` zotero collection 
   - See those authors (from Maud):
     - Christine Argillier (Irstea Aix/Provence)
     - Thierry Oberdorff (Toulouse ?)
     - Bernard Hugueny (IRD, Toulouse)
   - Ask to (by Maud):
     - Sébastien Brosse
     - Sébastien Villégier
4. Effects of perturbation
   - Coreids project (cf Maud)

## Immediate objectives

- [ ] map station and pressure to RHT:
  - [ ] Station
  - [ ] Water quality
- [ ] Environmental data
  - [ ] temporal flow and quality (Marie Silvestre):
    - [x] Interpolate flow and quality
  - [ ] How to analyze qualitative data:
    - [x] Habitat
  - [x] Pressure data (Olivier Dezerald & Philippe Usseglio-Polatera):
  - [ ] Temperature data?
    - [ ] https://hubeau.eaufrance.fr/page/api-temperature-continu
  - [x] ONDE for etiage: from 2012 to 2018 
  - [x] ROE for obstacle:
    - [ ] To explore
  - [x] ADES for map of rock types
    - http://www.ades.eaufrance.fr/
    - [x] professional access
    - [ ] Map of water quality and level 
- [ ] Make scripts more modular:
  - [ ] network_analysis become network_composition after adding node   
  - [ ] 02_run_analysis.R:
    - [ ] separate build_network from metrics computation
- [x] network methods:
  - [x] connectance, average trophic level, richness
    - [ ] beautiful plots
      - [ ] node size according to biomass 
        - [ ] connect biomass to graph plot
      - [ ] plot "tableau de bord"
        - [ ] réseau + some information
    - [/] nestedness, trophic length, modularity, trophic group:
      - [ ] compute betalink: [ingnacio bartomeus](https://github.com/ibartomeus/betalink/tree/new_features)
      - [ ] trophic group: [cf legendre website](https://www.biologie.ens.fr/~legendre/n_w/n_w.html) 
  - [ ] network analysis:
    - [ ] Compute trophic level by network
    - [ ] compute above network indices
    - [ ] post-modularity values? @poisot_an_2013
    - [ ] null model for nestedness
    - [ ] null model for connectance
    - [ ] null models everywhere ?
  - [ ] community methods:
    - [ ] compute turnover, rank shift, rate of change
- [x] Fish datasets to generate
- [ ] Assess quality of the dataset:

## Analysis road map

### Characterize pressures and pulse 

The idea is to characterize pressure by the average of quantitative pressures
such as water quality, polluants and landscape constraints (nb of obstacles,
concentration of agriculture). The pulse can be characterize by the 10th or 90th
percentile of the distribution of the quantitative perturbations.  

### Get perturbation data 

We need to map of the perturbation to a common spatial dataset together with
the sampled station. We will map all the data to the RHT (Réseau Hydrologique
théorique).

# Temporal stability and diversity 

## The big questions

- What are the effects of global changes on community stability?
  - What are the underlying mechanisms of the response of community stability to
    global changes?
  - Which facets of stability are affected by global changes?

- Are species role constant in time ? (e.g. keystone ?)


## Reading notes 

- A lot of studies assume that the community stability facing global changes is
  driven by richness and its effects on population asynchrony, but other suggest
  that there are **independant effects of forcing** and **richness** on community
  stability [@olivier_independent_nodate]. 
    - @olivier_independent_nodate suggest that effect of global changes on
      abundance can drive community stability (without effect on species
      richness)
    - Asynchrony is due to difference in response to forcing variables and/or
      changement of competitive hierarchy?
- Most research on the subject (link forcing, stability and species richness)
  has been done in controlled experiment (plant, mesocosm?)
    - Few test in local natural population
    - Cedar Creek's experiments [@tilman_biodiversity_2014]
- Ecology of perturbation is missing: notably its effects on abundance ?
  [@olivier_independent_nodate]

- **Facets of stability** [@donohue_navigating_2016]:
  - **Variability**: temporal or spatial Variability
    - Measurement: CV
  - **Resistance**: community structure change induced by a perturbation
    - Measurement: ratio of the variable value before and after perturbation
  - **Persistance**: time length, the community stays in the same state
    - Measurement: time until a change appear after invasion of a species or a
      loss a species
  - **Tipping point**: permanent change of system state
    - Measurement: bimodality for same environmental variable [@berdugo_plant_2017; @blonder_predictability_2017]
  - **Resilience**: multi-dimensional notion. Capacity of the system to keep the
    same relationship between population and state variables
    - Measurement:

- Temporal variability and food web structure:
  - Few studies exist [@mccann_the_2000] but some found a positive one

- Motifs: [@borelli_selection_2015, @delmas_analysing_2018]
  - subgraphs; basic building block; studying their distribution
  - link to trophic role
  - @holt_community_1997 defines the 13 motifs that can be encoutered in a
    network
  - @borelli_selection_2015 linked it to stability (eigen value of the matrix)

- Dissimilary in species interaction networks: @poisot_an_2012, (code)[https://github.com/ibartomeus/betalink/tree/new_features]

## Comment on fish protocol (AFB expertise)

### Comment on fish protocol evolution

Start the analysis in 1995 because before the protocol was to loosely common.
Some aspects are the lack of enough people to capture all the fish (some the
juveniles were not captures). The sampled surface was not measured and reported
(by eye estimation).

The DCE was introduced in 2007 and introduced new protocol standards. First, the
"ambiance" protocol (continuous fishing over the bank) was replaced by the
protocol "partial by points" which is a discrete fishing protocol. So, many big
stations had ambiance protocol until 2007 which were followed by the partial
protocol. Secondly, a sampling area was standardized to 10, 20 times of the
sampled stream width.


### Problem with fishing protocol merging

- Partial over bank: linear (i.e. continuous)
- Partial over point: discrete

There are some difficulties to merge those protocol.
The least bad methods would be to report data standardized by the sampling
effort. The partial protocol had a standardized sampled area by sampled point.
So, we can sum all the points and compare to the sampled area of the sampling by
bank.



# Fish data and network construction

## Fish Data information

The goal of this part is to describe the work that has been done previously
by @edeline_ecological_2013 and @bonnafe_trophic_nodate.

Those informations were extracted from the two studies previously cited  

- 4,145,234 individual body size measurements of fish
- 50 species
- 20,809 fisheries operation in 7,024 stations 
- 8 french basins (North, Seine River, Channel Sea, Atlantic Ocean, Loire
River, Garonne River, Rhone River, Mediterranean Sea)
- Catching by electric fishing 
  - 3 different strategies:
    - Boat
    - Walking
    - Mixed
  - 5 different methods:
    - Complete: whole station surface fully sampled
    - Ambiance: whole station surface partially sampled
    - Points: Point Abundance Sampling method (Nelva et al., 1979)
    - Bank: only river banks were sampled
    - Other: other partial sampling strategies depending on river width and
      depth
- Measurements:
  - Count
  - Body length (only on a fraction of the fish if they were too numerous)
- Exclusion: migratory species with a saltwater growth period
- Environmental data:
  - river slope
  - depth
  - channel width (at upper banks)
  - altitude
  - distance to the sea
  - distance to the source
  - anthropogenic usage of the watershed (Corine Land
Cover data)
  - air temperature that preceded each sampling operation as a proxy for
    river water temperature.

### Network construction [@bonnafe_trophic_nodate]

From literature, @bonnafe_trophic_nodate had rebuilding the global trophic
network (also called the "metaweb"). From the local cooccurence data, they built
the local trophic network.

- Node types:
  - Fish 
  - Resources
- Three types of interaction:
  - Fish-Fish  
  - Fish-Resources  
  - Resources-Resources  

#### Metaweb

The metaweb is a virtual web containing all the nodes of the dataset and links
between them as if they would cooccur all together.

- Components:
  1. A set of Nodes (N): Fish (F) and Resources (R)
  2. An interaction matrix (L)

- Two different metawebs:
  1. Fish nodes defined as 9 size class by species ($9\times50=450$)
  2. Fish nodes defined as 1 by species $50$)

Comparing the two metawebs permit to disentangle network answer in terms of
population size structure (2) from species composition (1).


##### Defining nodes

@bonnafe_trophic_nodate have looked for fish diet and ontogenic food diet in
literature. 

- Seven Resource nodes:
  - Detritus (R1)
  - Biofilm (R2)
  - Phytobenthos (R3)
  - Macrophyte (R4)
  - Phytoplankton (R5)
  - Zooplankton (R6)
  - Zoobenthos (R7)

- Fish nodes (metaweb 1), for each species (i = 1,2,3, ..., 9):
  - 9 size classes (j = 1,2,3, ..., 9)
  - Size classes attributed by size quantile distribution 
  - Total: $F_{ij} = {F11,...}$
- Fish nodes (metaweb 2), for each species (i = 1,2,3, ..., 9):
  - $F_{ij} = {F11, F21, F31, ...}$ (j is constant)

##### Defining links

Based on literature [@bonnafe_trophic_nodate].

- Resource - Resource:
  - Biofilm and Detritus do not feed on other nodes
  - phytoplankton, phytobenthos, and macrophytes -> detritus
  - zooplankton -> phytoplankton and itself 
  - Zoobenthos -> all Resource nodes (including itself)

- Resource - Fish:
  - Diet of each species and ontogenic shifts known by literature
  - Size of diet shift known for 22/50 species
    - Infered for the other species according stomach content records in literature

- Fish - Fish, for each species:
  1. occurrence of piscivory 
  2. ontogenic shift to piscivory
  3. derivation of a predation window

- The predation window model:
  - Predator and prey body size: $B_P$ and $B_N$
  - $\alpha \leqslant \frac{B_N}{B_P} \leqslant \beta$
  - $\alpha$ and $\beta$ define respectively the lower and upper range of the
    predation window
  1. The midpoint of the predator size class ($B_{P_{j,mid}}$) is projected on the predation
     window. 
     - It gives the $B_{N,min; P_{j,mid}}$ and $B_{N,max; P_{j,mid}}$ for the predator midclass 
     - $B_{N,min; P_{j,mid}} = \alpha B_{P_{j,mid}}$  **Not sure** 
     - $B_{N,max; P_{j,mid}} = \beta B_{P_{j,mid}}$  **Not sure**
  2. A trophic link between the predator ($B_{P_{j}}$) and the prey size class
     ($B_{N_{j}}$) is drawn if $B_{N,min; P_{j,mid}} \leqslant B_{N_{j,mid}}
     \leqslant B_{N,max; P_{j,mid}}$. 
     - IOW, if the mid of the prey size class fall in the predator window


# References
