---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(tidyverse)
library('lubridate')
library(magrittr)
library(sf)
mypath <- rprojroot::find_package_root_file
source(mypath("R", "misc.R"))
source(mypath("R", "geo_methods.R"))
source(mypath("R", "plot_methods.R"))
myload(quality_data, dir = mypath("data-raw"))
myload(prediction, dir = mypath("data-raw", "ssn_interpolation"))
```
```{r}
######################
#  Nitrate Bretagne  #
######################

myload(station_analysis, region_polygon, dir = mypath("data"))

bretagne <- filter(region_polygon, nom == "Bretagne") 
lgs <- st_within(station_analysis, st_transform(bretagne, crs = 2154))
mask <- lengths(lgs) > 0
bre_station <- filter(station_analysis, mask)
bre_prediction <- filter(prediction, id %in% bre_station$id) %>%
  filter(var_code == "NO3")

avg_year <- bre_prediction %>% group_by(year) %>% summarise(no3 = mean(avg_data))
ggplot(avg_year, aes(x = year, y = no3)) +
  geom_line()
  
ggplot(prediction, aes(x = avg_data)) +
  geom_histogram() +
  facet_wrap(~year, scales = "free_x")
summary(bre_prediction$avg_data)

which(prediction$avg_data > 100)
resume <- quality_data %>%
  group_by(var_code) %>%
  summarise(resume = list(summary(value)))
hist(quality_data[quality_data$var_code == "NO3", ]$value)
resume[resume$var_code %in% "NO3", ][["resume"]]
resume[resume$var_code %in% "NO2", ][["resume"]]
resume[resume$var_code %in% "PO4", ][["resume"]]
```
