---
title: "Preliminary results"
author: "Alain Danet"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Preliminary results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.dim = c(7, 7)
)
library(tidyverse)
library(ggpmisc)
library(cowplot)
library(kableExtra)
library(magrittr)
library(igraph)
library(NetIndices)
library(tidygraph)
library(ggraph)
library(lubridate)
devtools::load_all()
theme_set(theme_alain())
```

# Network exploration 

## Metaweb

```{r}
data(metaweb_analysis)
meta <- metaweb_analysis; rm(metaweb_analysis)

g <- igraph::graph_from_adjacency_matrix(meta$metaweb, mode = "directed")

# Define layout
lay <- layout.fruchterman.reingold(g)
# Compute trophic level
dead_material <- c("det", "biof")
lay[, 2] <- TrophInd(meta$metaweb, Dead = dead_material)$TL
# Plot
par(mar=rep(5, 4))
plot.igraph(g,layout=lay,vertex.label=NA,vertex.size=2,edge.arrow.size=.5,edge.width=.5)

```

## Local network

```{r}
data(network_analysis)
net <- network_analysis %>%
  dplyr::select(opcod, network) %>%
  unnest() %>%
  left_join(., dplyr::select(op_analysis, opcod, station, year)) %>%
 dplyr::select(from, to, everything())

# Get a station
net_ex <- filter(net, station == unique(net$station) %>% sample(., 1))
## Graph -------------------------
net_graph <- graph_from_data_frame(net_ex, directed = TRUE)
 
## Layout --------------------------------
lay <- create_layout(graph_from_adjacency_matrix(meta$metaweb, mode = "directed"), layout = "kk")
node_pos <- TrophInd(meta$metaweb,
  Dead = dead_material)$TL - 1
lay$y <- node_pos
lay$species <- get_species(lay$name)

net_graph <- select(net_ex, from, to, year) %>%
  arrange(year) %>%
  group_by(year) %>%
  nest() %>%
  mutate(
    net_graph = pmap(list(net = data, title = year), 
    set_layout_graph, glay = lay, color_scale = set_color_species(lay))
  )
## Get legend
species_colour_legend <- get_legend(net_graph[1,]$net_graph[[1]])
## Remove legend in the other plots
net_graph %<>%
  mutate(net_graph = map(net_graph, function(x) x + theme(legend.position = "none")))
plot_grid(plotlist = net_graph[1:4,]$net_graph,
species_colour_legend)
plot_grid(net_graph[1, ]$net_graph[[1]])
```

# Correlation between network indices

```{r}
# Get network metrics
data(temporal_network_metrics)
data(temporal_community_metrics)
cor_avg <- temporal_network_metrics %>%
  select_at(vars(matches("avg"))) %>%
  cor()
#knitr::kable(cor_avg)
as.data.frame(round(cor_avg,2)) %>%
  mutate_all(funs(cell_spec(., "html", color = ifelse(abs(.) > .65 & . != 1, "red",
	  "black")))) %>%
  mutate(variable = colnames(.)) %>%
  select(variable, everything()) %>%
  kable(format = "html", escape = F)

```

```{r}
cor_cv <- temporal_network_metrics %>%
  select_at(vars(matches("cv"))) %>%
  cor()
as.data.frame(round(cor_cv,2)) %>%
  mutate_all(funs(cell_spec(., "html", color = ifelse(abs(.) > .65 & . != 1, "red",
	  "black")))) %>%
  mutate(variable = colnames(.)) %>%
  select(variable, everything()) %>%
  kable(format = "html", escape = F)
```


# Classic biomass and community

```{r}
biomass_com <- temporal_community_metrics %>%
  select(richness_avg, biomass_cv, richness_cv, betadiv) %>%
  gather(type, diversity, richness_avg, richness_cv, betadiv)
formula <- y ~ x #needed for stat_poly_eq
qplot(diversity, biomass_cv, data =  biomass_com, geom = "point") +
  facet_grid(cols = vars(type), labeller = mylabel(), scales = "free_x") +
  geom_smooth(method = 'lm') +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  xylabs(x = "diversity", y = "biomass_cv")
```

# Biomass and network structure

```{r,}
# plot
avg_network <- temporal_network_metrics %>%
  select_at(vars(matches("avg|station")))
biomass_cv_station <- temporal_community_metrics %>%
  select(station, biomass_cv)
cv_biomass_net_avg <- left_join(avg_network, biomass_cv_station) %>%
  gather(metrics, values, colnames(select_at(., vars((matches("avg")))))) %>%
  mutate(metrics = str_replace(metrics, "_avg", "")) %>%
  filter(metrics != "nbnode")

# TODO: think about not facetting (list of plots ?)
# Facet label:
formula <- y ~ x #needed for stat_poly_eq
p <- ggplot(cv_biomass_net_avg, aes(y = biomass_cv, x = values)) +
  geom_point() +
  facet_grid(cols = vars(metrics), scales = "free_x") +
  geom_smooth(method = 'lm') +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(
    x = "Average of the network indices",
    y = "CV of the community biomass"
  )
p

```

# Compartimentalization

```{r}
```

