---
title: "Synchrony"
author: "Alain Danet"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Synchrony}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
mypath <- rprojroot::find_package_root_file
data_common <- mypath("data")
dest_dir <- mypath("data", "species")
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.dim = c(10, 10),
  echo = FALSE
)
library(tidyverse)
library(ggpmisc)
library(cowplot)
library(kableExtra)
library(magrittr)
source(mypath("R", "misc.R"))
source(mypath("R", "plot_methods.R"))
#devtools::load_all()
theme_set(theme_alain())
```

```{r load dataset, include = FALSE}
myload(synchrony, temporal_community_metrics, dir = mypath("data"))
```
```{r compare both stability measure}
synchrony %<>%
  mutate(stab_com = 1 / cv_com)
compare_stab <- synchrony %>%
  left_join(select(temporal_community_metrics, station, biomass_stab), by =
    "station")
ggplot(compare_stab, aes(x = stab_com, y = biomass_stab)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  labs(x = "Thibault & Connelly",
    y = "Classic measure",
  title = "Compare the two stability measurement: 1/CV")
```

```{r compare distributions of the stability measurements}
compare_stab2 <- compare_stab %>%
  gather(stab, value, stab_com, biomass_stab)

ggplot(compare_stab2, aes(x = value)) +
  geom_histogram() +
  facet_wrap(~ stab)
```

```{r richness_med versus stability}
compare_stab_div <- compare_stab2 %>%
  left_join(select(temporal_community_metrics, station, richness_med),
    by = "station")
formula <- y ~ x #needed for stat_poly_eq
ggplot(compare_stab_div, aes(y = value, x = richness_med)) +
  geom_point() +
  facet_wrap(~ stab) +
  geom_smooth(method = 'lm', formula = formula) +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(x = "Median richness", y = "Biomass stability")
```



```{r synchrony and diversity}
sync <- synchrony %>% 
  select(station, synchrony) %>%
  left_join(select(temporal_community_metrics, station, richness_med),
    by = "station")

sync_plot <- ggplot(sync, aes(y = synchrony, x = richness_med)) +
  geom_point() +
  geom_smooth(method = 'lm', formula = formula) +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(x = "Median richness", y = "Synchrony")
```

```{r}
cv <- synchrony %>% 
  select(station, cv_sp, stab_com) %>%
  left_join(select(temporal_community_metrics, station, richness_med,
      biomass_stab),
    by = "station") %>%
  gather(cv, value, cv_sp, stab_com, biomass_stab)
cv_plot <- ggplot(cv, aes(y = value, x = richness_med)) +
  geom_point() +
  facet_wrap(~ cv, scales = "free_y") +
  geom_smooth(method = 'lm', formula = formula) +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(x = "Median richness", y = "Coefficient of Variation")
```

```{r}
plot_grid(sync_plot, cv_plot, ncol = 1)
```

### Synchrony and richness by trophic groups

```{r}
myload(troph_group_synchrony, dir = mypath("data"))

sync_troph <- synchrony %>% 
  select(station, synchrony, cv_com, cv_sp) %>%
  left_join(
    select(troph_group_synchrony, station, med_nbsp_high_troph, med_nbsp_low_troph, med_nbsp_total),
    by = "station") %>%
  gather(troph, div, med_nbsp_high_troph, med_nbsp_low_troph,
    med_nbsp_total) %>%
  gather(stab, value, synchrony, cv_com, cv_sp)

formula <- y ~ x + I(exp(-x)) #needed for stat_poly_eq
sync_div_plot <- ggplot(sync_troph, aes(y = value, x = div)) +
  geom_point() +
  facet_grid(stab ~ troph, scales = "free_y") +
  geom_smooth(method = 'lm', formula = formula) +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(x = "Median richness", y = "")
sync_div_plot
```


## Synchrony by trophic groups

```{r}
troph_group_synchrony %<>%
  mutate(stab_com = 1 / cv_com)
```

```{r synchrony and diversity 2}
sync_div <- troph_group_synchrony %>%
  select(station, synchrony, med_nbsp_high_troph, med_nbsp_low_troph,
    med_nbsp_total) %>%
  gather(troph, div, med_nbsp_high_troph, med_nbsp_low_troph,
    med_nbsp_total)
formula <- y ~ x #needed for stat_poly_eq
sync_div_plot <- ggplot(sync_div, aes(y = synchrony, x = div)) +
  geom_point() +
  facet_wrap(~ troph, scales = "free_y") +
  geom_smooth(method = 'lm', formula = formula) +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(x = "Median richness", y = "Synchrony")
sync_div_plot
```

```{r Thibault & Connelly stability and diversity}
stab_div <- troph_group_synchrony %>%
  select(station, stab_com, med_nbsp_high_troph, med_nbsp_low_troph,
    med_nbsp_total) %>%
  gather(troph, div, med_nbsp_high_troph, med_nbsp_low_troph,
    med_nbsp_total)
formula <- y ~ x #needed for stat_poly_eq
stab_div_plot <- ggplot(stab_div, aes(y = stab_com, x = div)) +
  geom_point() +
  facet_wrap(~ troph, scales = "free_y") +
  geom_smooth(method = 'lm', formula = formula) +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(x = "Median richness", y = "Stability (1/cv_com)")
```

```{r Thibault & Connelly cv_com and diversity}
cv_div <- troph_group_synchrony %>%
  select(station, cv_com, med_nbsp_high_troph, med_nbsp_low_troph,
    med_nbsp_total) %>%
  gather(troph, div, med_nbsp_high_troph, med_nbsp_low_troph,
    med_nbsp_total)
formula <- y ~ x #needed for stat_poly_eq
cv_div_plot <- ggplot(cv_div, aes(y = cv_com, x = div)) +
  geom_point() +
  facet_wrap(~ troph, scales = "free_y") +
  geom_smooth(method = 'lm', formula = formula) +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(x = "Median richness", y = "cvility (1/cv_com)")
cv_div_plot
```
```{r}
plot_grid(stab_div_plot, cv_div_plot, ncol = 1)
```

# Check community

```{r}
station_id <- sync_troph %>%
  filter(troph == "med_nbsp_total", stab == "cv_com") %>%
  arrange(desc(div)) %>%
  slice(1:3)
station_id <- station_id$station 
```

```{r}
sync_temp <- sync_troph %>%
  filter( troph == "med_nbsp_total") %>%
  spread(stab, value)

norm_temp <- temporal_community_metrics %>%
  #filter(station %in% station_id) %>%
  select(station, biomass_cv)
comp_temp <- left_join(sync_temp, norm_temp) %>%
  mutate(
    sync1 = ifelse(synchrony > 0.99 | synchrony < 0.2 , TRUE, FALSE),
    lowdiv = ifelse(div < 3, TRUE, FALSE)
    ) %>%
  gather(stab, value, cv_com, cv_sp)
ggplot(comp_temp, aes(y = biomass_cv, x = value)) +
  geom_point(aes(color = sync1)) +
  geom_abline(intercept = 0, slope = 1) +
  facet_grid(~stab)
```

```{r}
ggplot(comp_temp, aes(y = biomass_cv, x = value)) +
  geom_point(aes(color = lowdiv)) +
  geom_abline(intercept = 0, slope = 1) +
  facet_grid(~stab)
```



