---
title: "Produce talk figures"
author: "Alain Danet"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Produce talk figures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.dim = c(7, 7)
)
library(tidyverse)
library(ggpmisc)
library(cowplot)
library(magrittr)
library(igraph)
library(NetIndices)
library(tidygraph)
library(ggraph)
library(lubridate)
#devtools::load_all()
mypath <- rprojroot::find_package_root_file
data_common <- mypath("data")
dest_dir <- mypath("data", "species")

source(mypath("R", "misc.R"))
source(mypath("R", "plot_methods.R"))
source(mypath("R", "geo_methods.R"))
source(mypath("R", "press_methods.R"))
source(mypath("R", "synchrony.R"))
source(mypath("R", "community_methods.R"))
source(mypath("R", "community_analysis.R"))
source(mypath("R", "statistical_analysis.R"))
theme_set(theme_alain())


```

```{r load data}
myload(metaweb_analysis, op_analysis, temporal_community_metrics, diet_shift,
  dir = data_common)
myload(network_analysis, temporal_network_metrics, dir = dest_dir)
```

```{r}
myload(nmds, habitat_pressure, dir = mypath("report"))
st_basin <- get_basin_station(sf_obj = FALSE)
myload(op_analysis, op_analysis_wo_holes, dir = mypath("data"))
myload(biomass_ts_sax, dir = mypath("data"))
op_analysis_bbb <- filter(op_analysis, station %in%
  biomass_ts_sax[biomass_ts_sax$sax == "bbb",]$station)
op_analysis_wo_holes_bbb <- filter(op_analysis_wo_holes, station %in%
  biomass_ts_sax[biomass_ts_sax$sax == "bbb",]$station)

# Compute stability, network metrics, etc with ;he new datasets
com_data <- compute_community_temporal_analysis(.op = op_analysis_bbb)
# Compute sem dataset 
sem_data <- compute_sem_dataset(
  com = com_data[["tps_com"]],
  network = com_data[["tps_net"]],
  hab_press = habitat_pressure,
  sync = com_data[["sync"]],
  nmds = NULL,
  basin = st_basin
  )

stab_div_troph <- com_data$tps_bm_troph %>%
  filter(troph_group != 1) %>%
  mutate(troph_group = as.factor(troph_group),
    log_rich = log10(richness_med),
    log_rich_tot = log10(richness_tot),
    log_bm = log10(biomass_med),
    log_stab = log10(biomass_stab)) %>%
  dplyr::select(station, troph_group, biomass_stab, richness_med, richness_tot, log_rich, log_rich_tot, log_stab, log_bm, biomass_med, richness_tot) %>%
  dplyr::left_join(st_basin, by = "station")
```

## Ontogenic shift data

```{r}
diet_tex <- xtable::xtable(
  dplyr::select(diet_shift[1:20,], -remark, -light, -species_name),
  caption = "Subset of ontogenic shift data.",
  auto = TRUE
)
print(
  diet_tex,
  file = "~/Documents/thesis/talks/fishcom_fig/diet_shift.tex",
  compress = FALSE,
  include.rownames = getOption("xtable.include.rownames", FALSE))
#?print.xtable
```


## Temporal network 

```{r}
meta <- metaweb_analysis
dead_material <- c("det", "biof")
```

```{r}
net <- network_analysis %>%
  dplyr::select(opcod, network) %>%
  unnest() %>%
  left_join(dplyr::select(op_analysis, opcod, station, date)) %>%
 dplyr::select(from, to, everything())

meta <- metaweb_analysis
# Get a station
#7800
#6966
net_ex <- filter(net, station == unique(net$station) %>% sample(., 1)) %>%
  mutate(date = year(date))

net_ex <- filter(net, station == 6966) %>%
  mutate(date = year(date)) %>%
  filter(! date %in% c(2015, 2016))

p2 <- my_crap_temporal_network(net = net_ex, metaweb = meta$metaweb, network_data
  = network_analysis)
save_plot("~/Documents/thesis/talks/fishcom_fig/temporal_colors.pdf",
  p2, base_height = 8, base_width = 12, bg = "transparent")
```


```{r station_loc}
myload(station_analysis, dir = mypath("data"))
myload(region_polygon, dir = mypath("data"))
sf::st_crs(station_analysis)
station_analysis %<>%
  sf::st_transform(crs = 2154)
region_polygon %<>%
  sf::st_transform(crs = 2154)
plot(sf::st_union(region_polygon))
plot(sf::st_geometry(station_analysis), add = TRUE)
map_station <- ggplot() +
  geom_sf(data = region_polygon)+
  geom_sf(data = sf::st_geometry(station_analysis))

save_plot("~/Documents/thesis/talks/fishcom_fig/fish_station.pdf", map_station, base_height = 3, bg = "transparent", ncol = 1)
```

```{r species}
species <- read_delim("../bonnafe_work/data/raw_data/Code_sp.txt", delim = "\t")
filter(diet_shift, species %in% c("VAI", "TRF", "CHA")) %>%
  dplyr::select(species, species_name)
# CHA: Chabot commun
# TRF: Truite commune
# VAI: Vairon
```


# Stability

## Species richness

```{r}
richness_lab <- "Total richness (Log 10)"
stab_lab <- "Biomass stability (Log 10)"
bm_lab <- "Total biomass (Log 10)"
```


```{r p-s-div}
lim_log_stab <- get_min_max(list(sem_data, stab_div_troph), var_chr = "log_stab")
lim_log_rich_tot <- get_min_max(list(sem_data, stab_div_troph), var_chr = "log_rich_tot")
# Plot left  

p_stab_div <- sem_data %>%
  ggplot(aes(x = log_rich_tot, y = log_stab))+
  geom_point() +
  ylim(lim_log_stab) +
  xlim(lim_log_rich_tot) +
  labs(x = richness_lab, y = stab_lab) +
  geom_line(data = stab_div_pred) +
  geom_ribbon(data = stab_div_pred, aes(ymin = conf.low, ymax = conf.high), fill
  = "grey20", alpha = .2) +
  annotate("text", x = 1.0, y = .8, label = make_label_rsq(rsq = stab_div_sum),
    parse = TRUE)

# Right plot
p_stab_div_troph <- stab_div_troph %>%
  ggplot(aes(x = log_rich_tot, y = log_stab, color = troph_group)) +
  geom_point() +
  ggplot2::scale_color_manual(
    labels = troph_group_labeller(),
    values = c("blue", "green", "red"),
    name = "Trophic group"
  ) +
  ylim(lim_log_stab) +
  xlim(lim_log_rich_tot) +
  geom_line(data = stab_troph_pred) +
  geom_ribbon(data = stab_troph_pred,
    aes(ymin = conf.low, ymax = conf.high, color = NULL, group = troph_group),
    alpha = .2) +
  annotate("text", x = 0.8, y = .8, label = make_label_rsq(rsq = stab_troph_sum),
    parse = TRUE) +
  #scale_x_log10() + scale_y_log10() +
  labs(x = richness_lab, y = stab_lab)

p_stab <- plot_grid(p_stab_div, p_stab_div_troph,
  ncol = 2, rel_widths = c(.4, .6),
  labels = c("A", "B") 
)
```

```{r}
myload(temporal_network_metrics, dir = mypath("data", "classes") )
biomass_com <- temporal_community_metrics %>%
  select(station, biomass_stab) %>%
  left_join(select(temporal_network_metrics, station, mean_troph_level_corrected_med,
      connectance_corrected_med)) %>%
  gather(type, diversity, mean_troph_level_corrected_med, connectance_corrected_med)
formula <- y ~ x #needed for stat_poly_eq
p2 <- qplot(diversity, biomass_stab, data =  biomass_com, geom = "point") +
  facet_grid(rows = vars(type), labeller = mylabel(), scales = "free_x") +
  geom_smooth(method = 'lm') +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  xylabs(y = "biomass_stab") +
  xlab("Median network descriptors (corrected for species richness)")
p2
save_plot("~/Documents/thesis/talks/fishcom_fig/biomass_diversity2.pdf", p2, base_height = 3, bg = "transparent", ncol = 2)


```

```{r}
biomass_com <- temporal_community_metrics %>%
  select(station, biomass_stab) %>%
  left_join(select(temporal_network_metrics, station, mean_troph_level_corrected_med,
      connectance_corrected_med))
p2 <- qplot(mean_troph_level_corrected_med, biomass_stab, data =  biomass_com, geom = "point") +
  #facet_grid(rows = vars(type), labeller = mylabel(), scales = "free_x") +
  geom_smooth(method = 'lm') +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  xylabs(y = "biomass_stab") +
  xlab("Average trophic level (corrected for species richness)")
p2
save_plot("~/Documents/thesis/talks/fishcom_fig/stab_troph_level.pdf", p2, base_height = 3, bg = "transparent", ncol = 1)
```


## Stability & diversity by trophic group

```{r}
net_troph_group <- temporal_network_metrics_classes %>% 
  select(station, troph_group) %>%
  unnest() %>%
  filter(!is.na(troph_group), troph_group != 1) %>%
  mutate(troph_group = as.factor(troph_group))


troph_group_label <- c(
  "Low trophic level"    = "1",
  "Medium (2-3)" = "2",
  "High (3-4)"   = "3"
)

plot_stab_richness_troph_group1 <-
  ggplot(net_troph_group, aes(y = biomass_stab, x = richness_avg, color = troph_group)) +
  geom_point(size = 1) +
  geom_smooth(method = 'lm')+
  xylabs(
    x = "richness_avg",
    y = "biomass_stab"
  ) +
  scale_color_manual(
    name = "Trophic group",
    labels = names(troph_group_label)[-1],
    values = c("2" = "blue", "3" = "red")
    ) +
  annotate("text", x = 13, y = 5.5, label = "R^{2}==0.17", parse = TRUE)

plot_stab_richness_troph_group2 <- 
  plot_stab_richness_troph_group1 +
  theme(
    #legend.title = element_text(size=12, color = "salmon", face="bold"),
    legend.justification = c(.5,.5), 
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.background = element_blank(),
    legend.key = element_blank()
  )

save_plot("~/Documents/thesis/talks/fishcom_fig/biomass_diversity_troph_group.pdf",
  plot_stab_richness_troph_group2,
  base_height = 3,
  bg = "transparent",
  ncol = 1)
```

- The highest trophic level stability is 72% higher the low trophic level.
- Low trophic level with 10 species were in avg 15% more stable than the one with one
species 
- High trophic level with 10 species were in avg 35% less stable than one with
  one species 

