---
title: "Pressure visualisation"
author: "Alain Danet"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pressure visualisation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
mypath <- rprojroot::find_package_root_file
data_common <- mypath("data-raw", "polluants")
dest_dir <- mypath("data", "species")
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.dim = c(10, 10),
  echo = FALSE
)
library(tidyverse)
library(sf)
library(ggpmisc)
library(cowplot)
library(kableExtra)
library(magrittr)
source(mypath("R", "misc.R"))
source(mypath("R", "plot_methods.R"))
#devtools::load_all()
theme_set(theme_alain())
```

```{r load dataset, include = FALSE}
myload(yearly_press_interp, dir = data_common)
myload(synchrony, press_polluants, press_z_category, temporal_community_metrics, dir = mypath("data"))
```

```{r test for success by variable}
eff_interp <- yearly_press_interp %>%
  group_by(parameter) %>%
  summarise(frac_obs = sum(!is.na(value)) / n())
hist(eff_interp$frac_obs)
```

```{r which paramater has been badly interpolated}
kable(filter(eff_interp, frac_obs < .80))
```

# Plot some series

```{r}
test <- yearly_press_interp %>%
  filter(id %in% sample(id, 5), parameter %in% sample(parameter, 12))
ggplot(test, aes(x = year, y = value_corrected)) +
  geom_line(aes(color = as.factor(id))) +
  facet_wrap(~parameter, scales = "free_y")
```

# Plot some press

```{r enrichment}

myload(station_analysis, region_polygon, dir = mypath("data"))
station <- select(station_analysis, id)
station_press <- left_join(station, press_polluants)
unique(press_polluants$parameter)
parameter <- c("ammonium", "nitrates", "nitrites", "phosphore_total", "ph", "oxygene_dissous")

g <- purrr::map(parameter,
           function(x) {
	     ggplot(data = region_polygon) +
	       geom_sf() +
	       geom_sf(data = filter(station_press, parameter == x),
		 aes(color = press), size = 2) +
	       scale_color_gradient(low = "green", high = "red") +
	       ggtitle(x)
	   }
)

g2 <- cowplot::plot_grid(plotlist = g)
g2
```

```{r pesticides}
parameter <- c("atrazine", "glyphosate", "atrazine_desethyl", "carbofuran",
  "aldicarbe", "mancozebe", "fenpropimorphe"
)

g <- purrr::map(parameter,
           function(x) {
	     ggplot(data = region_polygon) +
	       geom_sf() +
	       geom_sf(data = filter(station_press, parameter == x),
		 aes(color = press), size = 2) +
	       scale_color_gradient(low = "green", high = "red") +
	       ggtitle(x)
	   }
)

g2 <- cowplot::plot_grid(plotlist = g)
g2

```

```{r vigne}


parameter <- c("cymoxanil", "captane", "folpel", "diuron",
  "aldicarbe", "mancozebe", "fenpropimorphe"
)

g <- purrr::map(parameter,
           function(x) {
	     ggplot(data = region_polygon) +
	       geom_sf() +
	       geom_sf(data = filter(station_press, parameter == x),
		 aes(color = press), size = 2) +
	       scale_color_gradient(low = "green", high = "red") +
	       ggtitle(x)
	   }
)

g2 <- cowplot::plot_grid(plotlist = g)
g2
```

# Press category

```{r}
myload(press_z_category, dir = mypath("data"))
```

```{r}
stab_cat_press <- synchrony %>%
  left_join(rename(press_z_category, station = id))

formula <- y ~ x #needed for stat_poly_eq
ggplot(stab_cat_press, aes(x = z_sum, y = cv_com)) +
  geom_point() + 
  facet_wrap(~category, scales = "fixed") +
  geom_smooth(method = 'lm', formula = formula) +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(x = "Z sum of pressure", y = "CV of the community")
```
```{r}
stab_cat_press_model <- stab_cat_press %>%
  select(-station, -synchrony, -cv_sp, -cv_classic) %>%
  filter(!is.na(category)) %>%
  spread(category, z_sum)
na.omit(stab_cat_press_model)
mod <- lm(cv_com ~ ., stab_cat_press_model)
p2 <- jtools::plot_summs(mod)
p2
```

```{r model with diversity}
stab_cat_press_model <- stab_cat_press %>%
  select(-synchrony, -cv_sp, -cv_classic) %>%
  filter(!is.na(category)) %>%
  spread(category, z_sum) %>%
  left_join(select(temporal_community_metrics, station, richness_med)) %>%
  select(-station)
na.omit(stab_cat_press_model)
mod <- lm(cv_com ~ ., stab_cat_press_model)
p2 <- jtools::plot_summs(mod)
p2
```

# With press 1090

```{r}
myload(press1090_z_category, dir = mypath("data"))
```
```{r}
stab_cat_press <- synchrony %>%
  left_join(rename(press1090_z_category, station = id))

formula <- y ~ x #needed for stat_poly_eq
ggplot(stab_cat_press, aes(x = z_sum, y = cv_com)) +
  geom_point() + 
  facet_wrap(~category, scales = "fixed") +
  geom_smooth(method = 'lm', formula = formula) +
  stat_poly_eq(
    formula = formula,
    eq.with.lhs = "italic(hat(y))~`=`~",
    aes(label = paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~")),
    parse = TRUE) +
  labs(x = "Z sum of pressure", y = "CV of the community")
```

```{r}
stab_cat_press_model <- stab_cat_press %>%
  select(-synchrony, -cv_sp, -cv_classic) %>%
  filter(!is.na(category)) %>%
  spread(category, z_sum) %>%
  left_join(select(temporal_community_metrics, station, richness_med)) %>%
  select(-station)
mod <- lm(cv_com ~ ., stab_cat_press_model)
p2 <- jtools::plot_summs(mod)
p2
```

