---
title: "Visualize flow data"
author: "Alain Danet"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualize flow data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
mypath <- rprojroot::find_package_root_file
data_common <- mypath("data-raw", "polluants")
dest_dir <- mypath("data", "species")
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.dim = c(10, 10),
  echo = FALSE
)
library(tidyverse)
library(lubridate)
library(ggpmisc)
library(cowplot)
library(kableExtra)
library(magrittr)
source(mypath("R", "misc.R"))
source(mypath("R", "plot_methods.R"))
#devtools::load_all()
theme_set(theme_alain())
```

```{r load dataset, include = FALSE}
myload(sample_flow_data, dir = mypath("data-raw", "flow_quality"))
```
```{r}
test <- sample_flow_data %>%
  filter(code %in% sample(unique(sample_flow_data$code), 12)) %>%
  gather(method, value, moving_avg, value)

ggplot(test, aes(x = meas_date, y = value)) +
  geom_line(aes(color = method)) +
  facet_wrap(~code)
```

```{r}
test <- sample_flow_data %>%
  filter(code %in% sample(unique(sample_flow_data$code), 12))

ggplot(test, aes(x = meas_date, y = value - moving_avg)) +
  geom_line() +
  facet_wrap(~code)
```

```{r}
ggplot(test, aes(x = meas_date, y = value - moving_avg)) +
  geom_line() +
  facet_wrap(~code, scales = "free_y")

```


## show quantiles

```{r}
ggplot(test, aes(sample = value - moving_avg)) +
  stat_qq() +
  facet_wrap(~code, scales = "free_y")
```

## Compute quantiles by station

```{r}
quant_seq <- c(0.01, 0.05, 0.95, 0.99)
test <- sample_flow_data %>%
  group_by(code) %>%
  summarise(quant = list(quantile(value - moving_avg, probs = quant_seq, na.rm = TRUE))) %>%
  mutate(quant = map(quant, function(x){
      names(x) <- quant_seq
      return(x)
}))
test %>%
  unnest(quant)
  filter(code %in% sample(unique(sample_flow_data$code), 12))
```

# Temperature

```{r}
myload(yearly_temp_press_interp_mv_avg, sample_monthly_avg_temp,
  dir = mypath("data-raw", "temp"))
test <- yearly_temp_press_interp_mv_avg %>%
  filter(id %in% sample(id, 12)) %>%
  filter(value.predSE < abs(value_corrected))
ggplot(test, aes(x = year, y = value_corrected)) +
  geom_line() +
  facet_wrap(~id, scales = "fixed") +
  labs(y = "Temperature (°C)")
```

```{r}
test <- yearly_temp_press_interp_mv_avg %>%
  filter(value.predSE < abs(value_corrected)) %>%
  mutate(year = ymd(paste0(year, "-06-15"))) %>%
  group_by(year) %>%
  summarise(temperature = mean(value_corrected, na.rm = TRUE))
test_monthly_raw <- sample_monthly_avg_temp %>%
  group_by(year_month) %>%
  summarise(temperature = mean(moving_avg, na.rm =TRUE)) %>%
  rename(year = year_month)
ggplot(test, aes(x = year, y = temperature)) +
  geom_line() +
  geom_line(data = test_monthly_raw, color = "red")
```

## Map temperature through years

Make too much time to run

```{r, eval = FALSE}
library(sf)
myload(station_analysis, region_polygon, dir = mypath("data"))
station <- select(station_analysis, id)
#station_temp <- left_join(station, yearly_temp_press_interp_mv_avg) %>%
  #select(id, year, value_corrected)

#g <- purrr::map(unique(station_temp$year)[7:12],
  #function(x) {
    #ggplot(data = region_polygon) +
      #geom_sf() +
      #geom_sf(data = filter(station_temp, year == x),
	#aes(color = value_corrected), size = 2) +
      #scale_color_gradient(low = "green", high = "red") +
      #ggtitle(x)
  #}
#)

#g2 <- cowplot::plot_grid(plotlist = g)
#g2
```


```{r, eval = FALSE}
#temp <- filter(station_temp, year %in% unique(station_temp$year)[c(1,2,22,23)]) 
#g3 <- ggplot() + 
  ##geom_sf(data = region_polygon) +
  #geom_sf(data = temp, aes(color = value_corrected)) + 
  #scale_color_gradient(low = "green", high = "red") +
  #facet_wrap(~year)
#g3
```


# Hourly temperature data

```{r}
myload(sample_hourly_temp_naiades, yearly_avg_temp, dir = mypath("data-raw",
    "naiades_temperatures"))

```

```{r}


```

## Avg through years

```{r}
ggplot(yearly_avg_temp, aes(x = year, y = value)) +
  geom_point() +


```

