---
title: "New first figure"
---

```{r}
library(tidyverse)
library(magrittr)
library(cowplot)

mypath <- rprojroot::find_package_root_file
data_common <- mypath("data")
dest_dir <- mypath("data", "species")

source(mypath("R", "misc.R"))
source_dir(mypath("R"))
theme_set(theme_cowplot())
.pardefault <- par()
```


```{r}
myload(community_metrics, op_analysis, sem_data, dir = mypath("data"))
community_metrics %<>%
    left_join(dplyr::select(op_analysis, station, opcod, year))
```

```{r}
get_bm_dyn_year <- function (com = NULL, station = NULL) {

  st <- station
  test <- com %>%
    filter(station == st)

  test %<>%
    mutate(sp_tibble = map(sp_vector, ~tibble(species = names(.x), biomass_sp = .x))) %>%
    unnest(sp_tibble) %>%
    mutate(bm_std_sp = biomass_sp / surface) %>%
    dplyr::select(station, year, species, bm_std_sp)

  test %<>% 
    pivot_wider(names_from = species, values_from = "bm_std_sp")%>%
    mutate_at(vars(matches("[A-Z]{3}", ignore.case = FALSE)), ~ifelse(is.na(.), 0, .)) %>%
    pivot_longer(cols = matches("[A-Z]{3}", ignore.case = FALSE), names_to = "species", values_to = "bm_std_sp")

  return(test)
}
get_network_summary <- function (com = NULL, station = NULL, stab = TRUE, com_avg = TRUE) {

  st <- station
  tmp <- com %>%
    filter(station == st) %>%
    mutate_if(is.double, ~round(., 2))

  label_stab <- c(
    "Stability" = tmp$bm_std_stab,
    "Synchrony" = tmp$sync, 
    "CVsp" = tmp$cv_sp,
    "Median total biomass" = tmp$prod_std #"' * (g/m^2) * '"
    )
  label_com <- c(
    "Median species richness" = tmp$richness_med,
    "Median connectance" = tmp$ct,
    "Median avg trophic level" = tmp$t_lvl
  )
  label <- NULL 

  if (stab) {
    label <- c(label, label_stab)
  
  }

  if (com_avg) {

    label <- c(label, label_com)
  
  }

  return(label)

}

plot_dyn_web  <- function (
  com = NULL, sem_df = NULL, station = NULL,
  stacked = FALSE, .log = FALSE, color_species = NULL, label = NULL,
  label_parsed = FALSE, label_size = 4.5, y_label = NULL, my_ylim = NULL) {

  # get bm dynamic 
  com <- get_bm_dyn_year(com = com, station = station)

  # get total biomass 
    total_bm <- com %>%
	  group_by(year) %>%
	  summarise(bm_std_sp = sum(bm_std_sp)) %>%
	  mutate(species = "Total")

  p <- com %>%
    ggplot(aes(x = year, y = bm_std_sp, color = species))

  if (stacked) {
    p <- p + 
      geom_area(aes(fill = species))
  } else {
    p <- p + 
      geom_line() +
      geom_line(data = total_bm, color = "black")
  }

  if ( !is.null(my_ylim) ) 
  {
    p <- p +
      ylim(my_ylim)
  }

  # Make it professional:
  p <- p +
    labs(y = expression(Biomass~density~(g/m^2)), x = "Year")

  if (!is.null(sem_df)) {

    label <- get_network_summary(com = sem_df, station = station) 
  }

  if (!is.null(label)) {

    if (is.null(y_label)) {
      y_label <- max(total_bm$bm_std_sp) + max(total_bm$bm_std_sp) * 5/100
    }
  
    p <- p +
    annotate("text", x = median(total_bm$year),
      y = y_label,
      label = label, parse = label_parsed, size = label_size)
  }

  if (.log) {
    p <- p + scale_y_log10()
  }

  if (!is.null(color_species)) {
    p <- p + 
      scale_fill_manual(values = color_species) +
      scale_color_manual(values = color_species)
  }

  return(p)


}

get_label_from_named_vector <- function ( label = NULL, collapse = "\n") {
  paste0(names(label), " = ", label, collapse = collapse)
} 
```


```{r}
label <- get_network_summary(com = sem_data, station = 1755)
lab <- get_label_from_named_vector(label = label[1:4])
plot_dyn_web(com = community_metrics, station = 1755, stacked = TRUE, label =
 lab, label_size = 4.5 )
plot_dyn_web(com = community_metrics, station = 1755, label = lab)
```

# Network

```{r}
source(mypath("R", "codeWeb.R"))
myload(toy_metaweb, dir = mypath("data"))

TL <- NetIndices::TrophInd(toy_metaweb$metaweb)$TL
PlotWeb(
  TL = TL,
  webTL = toy_metaweb$metaweb,
  colnode = rep("red", length(TL)),
  abund = rnorm(length(TL), 100, 10),
  collink="grey70",
  scale_abun = .2
) 
```


```{r}
get_adj_net_station <- function (net = NULL, station = NULL) {

  st <- station

  net <- net %>%
    filter(station %in% st) %>%
    dplyr::select(station, year, network) %>%
    unnest(cols = c(network))

  ## Compute metrics:
  net %>%
    dplyr::select(year, from, to) %>%
    arrange(year) %>%
    group_by(year) %>%
    nest(network = c(from, to)) %>%
    mutate(
      igraph_obj = map(network, igraph::graph_from_data_frame,
	directed = TRUE),
      adj_mat = map(igraph_obj, igraph::as_adjacency_matrix,
	sparse = FALSE),
      troph = map(adj_mat, ~NetIndices::TrophInd(.x)),
      obs_troph_level_vector = map(troph, function (x) {
	TL <- x$TL
	names(TL) <- rownames(x) 
	return(TL)
	})
    )
}

get_net_biomass <- function (net = NULL, station = NULL) {

  st <- station

  # Get bm
  net <- net %>%
    filter(station %in% st) %>%
    dplyr::select(year, composition) %>%
    unnest(cols = c(composition))  %>%
    dplyr::select(year, sp_class, bm_std)
    
   # Make list
    net %<>%
      arrange(year) %>%
      group_by(year) %>%
      nest(bm = c(sp_class, bm_std)) %>%
      mutate(bm = map(bm, deframe))
  net
} 

set_color_nodes <- function (
  node_list = NULL,
  color_species_resources = NULL
  ) {

  node_list_sp <- stringr::str_replace_all(node_list, "_\\d", "") 

  colour <- color_species_resources[node_list_sp]
  names(colour) <- node_list
  return(colour)
}

set_node_resources_abun <- function (
  node_list = NULL,
  node_abun = NULL, resource_abun = NULL) {

  abun <- vector("numeric", length(node_list))  
  names(abun) <- node_list 

  if (is.null(resource_abun)) {
    resource_abun <- mean(node_abun)
  }

  abun[names(node_abun)] <- node_abun 
  abun[abun == 0] <- resource_abun 
  return(abun)

}

get_network_temporal_plot <- function (
  net_list = NULL,
  station = NULL,
  selected_years = NULL,
  node_color = NULL,
  scale_node_size = 0.01,
  par_options = par(mar = c(0,0,4,0)),
  add_title = FALSE,
  rel_abun = FALSE,
  log_abun = FALSE
  ) {

  net <- get_adj_net_station(net = net_list, station = station)
  bm <- get_net_biomass(net = net_list, station = station)

  if (!is.null(selected_years)) {
    net %<>% filter(year %in% selected_years) 
    bm %<>% filter(year %in% selected_years) 
  }

  if (is.null(node_color)) {
    node_color <- set_color_species(
      node_list = unique(names(unlist(net$obs_troph_level_vector))),
      species_list = NULL, resource_list = NULL, col_resource = NULL)
  }

  list_p <- list()
  index <- seq_along(net$year)


  for (i in index) {
    if(!is.null(par_options)) {
      par_options
    }
    plot.new()
    PlotWeb(
      TL = net$obs_troph_level_vector[[index[i]]],
      webTL = net$adj_mat[[index[i]]],
      colnode = set_color_nodes(
	node_list = names(net$obs_troph_level_vector[[index[i]]]),
	color_species_resources = node_color),
      abund = set_node_resources_abun(
	node_list = names(net$obs_troph_level_vector[[index[i]]]),
	node_abun = bm$bm[[index[i]]],
	resource_abun = 1
	),
      collink="grey70",
      scale_abun = scale_node_size,
      rel_abun = rel_abun,
      log_abun = log_abun
    )
    if (add_title) {
     title(main = paste0(net$year[[index[i]]]))
    }

    p <- recordPlot()

    list_p[[i]] <- p 
  }

  gg <- map(list_p, ggdraw)
  gg
}
```


```{r}
myload(network_analysis, dir = mypath("data", "classes"))
network_analysis %<>%
  left_join(dplyr::select(op_analysis, opcod, station, year)) %>%
  filter(!is.na(opcod))


net <- get_adj_net_station(net = network_analysis, station = 1755)
bm <- get_net_biomass(net = network_analysis, station = 1755)


meta_node_color <- set_color_species(node_list = unique(names(unlist(net$obs_troph_level_vector))), species_list = NULL, resource_list = NULL, col_resource = NULL)

PlotWeb(
  TL = net$obs_troph_level_vector[[1]],
  webTL = net$adj_mat[[1]],
  colnode = set_color_nodes(
    node_list = names(net$obs_troph_level_vector[[1]]),
    color_species_resources = meta_node_color),
  abund = set_node_resources_abun(node_list = names(net$obs_troph_level_vector[[1]]), node_abun = bm$bm[[1]]),
  collink="grey70",
  scale_abun = .2
) 
```

# Test fig plot 

```{r}
sp_color <- set_color_species(
  node_list = colnames(metaweb_analysis$metaweb),
  resource_list = metaweb_analysis$resource
)
node_sp <- str_extract(colnames(metaweb_analysis$metaweb), "[A-Z|a-z]*")
sp_color[node_sp]

myload(metaweb_analysis,  dir = mypath("data"))
TL <- NetIndices::TrophInd(metaweb_analysis$metaweb)$TL
PlotWeb(
  TL = TL,
  webTL = metaweb_analysis$metaweb,
  colnode = sp_color[node_sp],
  abund = 1,
  collink="grey70",
  scale_abun = .005
) 
```

```{r}
```



```{r, warning = FALSE}
nb <- seq.int(from = 1, to = length(net$adj_mat), length.out = 4)
```

```{r, fig.width = 10}
list_p <- list()
for (i in seq_along(nb)) {
#  par(mar = c(0,0,0,0))
  plot.new()
  PlotWeb(
    TL = net$obs_troph_level_vector[[nb[i]]],
    webTL = net$adj_mat[[nb[i]]],
    colnode = set_color_nodes(
      node_list = names(net$obs_troph_level_vector[[nb[i]]]),
      color_species_resources = meta_node_color),
    abund = set_node_resources_abun(
      node_list = names(net$obs_troph_level_vector[[nb[i]]]),
      node_abun = bm$bm[[nb[i]]],
      resource_abun = 1
      ),
    collink="grey70",
    scale_abun = .01,
    rel_abun = FALSE
    
  )
#  title(paste0(net$year[[nb[i]]]))

  p <- recordPlot()

  list_p[[i]] <- p 
}

gg <- map(list_p, ggdraw)
plot_grid(plotlist = gg, nrow = 2)
```


```{r, fig.width = 10, fig.height = 5, warning = FALSE}
#par(.pardefault)
#par(.pardefault)

meta_node_color <- set_color_species(node_list = unique(names(unlist(net$obs_troph_level_vector))), species_list = NULL, resource_list = NULL, col_resource = NULL)

p <- get_network_temporal_plot(net_list = network_analysis, station = 1755,
  selected_years = c(1997, 2010, 2018),
  node_color = meta_node_color, scale_node_size = 0.04, par_options = par(mar = c(0,0,0,0)))
#low <- plot_grid(plot_grid(plotlist = gg, nrow = 1), NULL, rel_width= c(1, .1))
low <- plot_grid(plotlist = p, nrow = 1)
test_p <- plot_grid(
  nrow = 2,
  plot_dyn_web(com = community_metrics, sem_df = sem_data, stacked = TRUE, station = 1755) +
    scale_fill_manual(values = meta_node_color) +
    scale_color_manual(values = meta_node_color)
    ,
  low,
  rel_heights = c(1, .6),
  align = "h"
)
test_p
save_plot(
  "figs/test_temporal_plot.png", test_p,
  nrow = 2, 
  ncol = 1,
  base_height = 4,
  base_width = 7)
```

```{r}
first_st <- sem_data %>%
  arrange(richness_tot, desc(biomass_stab)) %>%
  filter(richness_tot >= 2)

tes <- map(first_st$station[1:12], ~plot_dyn_web(
    com = community_metrics,
    sem_df = sem_data,
    station = .x,
    stacked = TRUE))
plot_grid(plotlist = tes)
```

```{r}
first_st$station[5]
#11432 my choice
```

```{r}
last_st <- sem_data %>%
  arrange(desc(prod), biomass_stab ) %>%
  filter(richness_tot < 15)

tes <- map(last_st$station[1:12], ~plot_dyn_web(
    com = community_metrics,
    sem_df = sem_data,
    station = .x,
    stacked = TRUE))
plot_grid(plotlist = tes)
```
```{r}
last_st$station[5]
#6268 my choice
```

```{r pca}
myload(habitat_press, dir = mypath("data"))
library(sf)
library(ggspatial)
# map
myload(p_st, dir = mypath("manuscript", "bef_stability", "figs"))
qt_station <- sem_data %>%
  filter(station %in% c(first_st$station[5], last_st$station[5])) %>%
  dplyr::select(station, bm_std_stab)
mysave(qt_station, dir = mypath("data"), overwrite = TRUE)
# Station
myload(biomass_ts_sax, op_analysis, dir = mypath("data"))

op_analysis_bbb <- filter(op_analysis, station %in%
  biomass_ts_sax[biomass_ts_sax$sax == "bbb",]$station)
station <- get_basin_station(sf_obj = TRUE)
station %<>%
  filter(station %in% unique(op_analysis$station))
## Get bbb
station %<>%
  mutate(type = ifelse(
      station %in% unique(op_analysis_bbb$station),
      "stable", "unstable"),
    st_temporal = ifelse(station %in% qt_station$station, TRUE, FALSE)
  )

habitat_press %<>% na.omit()
mask <- names(habitat_press) %in% names(get_pca_var_name_replacement())



p_st2 <- p_st +
  geom_sf(data = filter(station, type == "stable"), color = "black") +
  geom_sf(data = filter(station, station %in% qt_station$station),
    color = "red", size = 3) +
  geom_sf_text(data = filter(
      station, station %in% qt_station$station
      ), 
    aes(label = c("C", "D")),
    #color = "red",
    fontface = 2,
    size = 5,
    nudge_x = c(-30000, 30000),
    nudge_y = c(30000, -30000)
    ) +
  coord_sf(
    xlim = c(60000, 1100000),
    ylim = c(6100000, 7122216),
    datum = sf::st_crs(2154),
    crs = 2154,
    expand = FALSE
  ) +
  theme_void() +
  theme(plot.margin = theme_get()$plot.margin, legend.position = "none")

pca_rotated <- compute_rotated_pca(
  .data = habitat_press[, mask],
  naxis = 2
)
pca_rotated$rotated$loadings[, 2] <- pca_rotated$rotated$loadings[, 2] * (-1) 
p1 <- my_pca_plot(.data = pca_rotated$rotated,
  xaxis = "RC1", yaxis = "RC2", ctb_thld = .4, 
  label_size = 4, force_pull = 0.01, force = 10,
  seed = 1
)
save_plot(file = mypath("manuscript", "bef_stability", "figs", 
	"my_sweet_rotated_pca_reversed_axis2.pdf"),
    plot = p1,
    base_height = 4.5, base_asp = 1.2#1.618 
    )

cow_p1 <- plot_grid(NULL, p1, NULL, ncol = 1, rel_heights = c(.02, 1, .02))
fig1ab <- plot_grid(p_st2, cow_p1, ncol = 2, 
  labels = c("A", "B")
)
save_plot(mypath("manuscript", "bef_stability", "figs/fig1ab.png"), fig1ab,
  nrow = 1, 
  ncol = 2,
  base_height = 4,
  base_width = 4
)

``` 
```{r set-up}
st <- c(first_st$station[5], last_st$station[5]) 
library(viridis)
library(ggsci)
library(RColorBrewer)
display.brewer.pal(n = 8, name = 'Dark2')
display.brewer.pal(n = 8, name = 'Set2')

brew_col <- c(brewer.pal(n = 8, name = "Dark2"), brewer.pal(n = 8, name = "Set2"))

ti <- get_adj_net_station(net = network_analysis, station = st)
node_list <- unique(names(unlist(ti$obs_troph_level_vector)))

# Color
meta_node_color <- set_color_species(
  node_list = node_list, 
  species_list = NULL,
  resource_list = NULL,
  col_resource = NULL)
fish_node_mask <- str_detect(names(meta_node_color), "[A-Z]{3}")
meta_node_color[fish_node_mask] <- brew_col[1:sum(fish_node_mask)]
meta_node_color <- c(meta_node_color, PHX = brew_col[length(brew_col)])

#y max:
ymax <- community_metrics %>%
  filter(station %in% st) %>%
  summarise(bm = max(bm_std)) %>%
  deframe 
ymax <- round(ymax * .1) * 10
my_y_label <- ymax - 7 
my_label_size <- 4 

```
```{r low-rich-high-stab}

# Label
label <- get_network_summary(com = sem_data, station = st[1])
lab <- get_label_from_named_vector(label = label[1:5])

te <- plot_dyn_web(
  com = community_metrics,
  label = lab,
  y_label = my_y_label,
  label_size = my_label_size,
  my_ylim = c(0, ymax),
  station = st[1],
  stacked = TRUE,
  color = meta_node_color)
p <- get_network_temporal_plot(net_list = network_analysis, station = st[1],
  selected_years = c(1997, 1999, 2002),
  node_color = meta_node_color, scale_node_size = 0.06,
  par_options = par(mar = c(0,0,0,0)),
  log_abun = TRUE
)
#g <- map(p, ggdraw)
#g <- plot_grid(g[[1]], NULL, g[[2]], NULL, g[[3]], nrow = 1, rel_width = c(1, -.2, 1, -.2, 1))
g <- plot_grid(plotlist = map(p, ggdraw), nrow = 1)

cow_te  <- te +
  theme(legend.position = "none")
fig1c <- plot_grid(
  cow_te,
  g,
  nrow = 2,
  align = "h",
  rel_heights = c(1, .6)

)
fig1c
save_plot("figs/fig1c_low_rich.pdf", fig1c,
  nrow = 2, 
  ncol = 1,
  base_height = 4,
  base_width = 7
)
```

```{r}
# Label
label2 <- get_network_summary(com = sem_data, station = st[2])
lab2 <- get_label_from_named_vector(label = label2[1:5])

te2 <- plot_dyn_web(
  com = mutate(community_metrics, year = as.integer(year)),
  label = lab2,
  y_label = my_y_label,
  label_size = my_label_size,
  my_ylim = c(0, ymax),
  station = st[2],
  stacked = TRUE,
  color = meta_node_color) +
scale_x_continuous(breaks = c(1995, 1998, 2001, 2004))
p2 <- get_network_temporal_plot(net_list = network_analysis, station = st[2],
  selected_years = c(1997, 1999, 2002),
  node_color = meta_node_color, scale_node_size = 0.05,
  par_options = par(mar = c(0,0,0,0)),
  log_abun = TRUE
)
#g <- map(p, ggdraw)
#g <- plot_grid(g[[1]], NULL, g[[2]], NULL, g[[3]], nrow = 1, rel_width = c(1, -.2, 1, -.2, 1))
g2 <- plot_grid(plotlist = map(p2, ggdraw), nrow = 1)

# get legend
cow_te2 <- te2 + theme(legend.position = "bottom") +
  guides(
    fill = guide_legend(nrow = 2, title = "Species"),
    color = guide_legend(nrow = 3, title = "Species")
  )
leg_species <- get_legend(cow_te2)
cow_te2 <- te2 + theme(legend.position = "none")

fig1d <- plot_grid(
  cow_te2,
  g2,
  nrow = 2,
  align = "h",
  rel_heights = c(1, .60)

)
save_plot("figs/fig1d_high_rich.pdf", fig1d,
  nrow = 2, 
  ncol = 1,
  base_height = 4,
  base_width = 7
)
```


```{r}
cow_fig1ab <- plot_grid(
  p_st2 + theme(panel.background = element_rect(fill = "white")),
  p1, NULL,
  rel_widths = c(.5, .5, .07),
  ncol = 3,
  labels = c("A", "B", ""))
fig1cd <- plot_grid(fig1c, fig1d, ncol = 2, labels = c("C", "D"))
cow_leg_species <- plot_grid(NULL, leg_species, NULL, nrow = 1, rel_widths = c(.25, .5, .25))
fig1 <- plot_grid(cow_fig1ab, fig1cd, cow_leg_species,
  nrow = 3,
  rel_heights = c(.35, .60,.05),
  align = "h"
)
# ele: single column (82 mm), two-thirds page width (110 mm) or full page width (173 mm)
dev.new(width = 8.2, height = 11.0, units = "cm")
# i3: mod + shift + space 
png(file = “C://R//SAVEHERE//myplot.jpeg”)
plot(x,y)
dev.off()

# Draw connectance and average trophic level:
lab_net <- get_label_from_named_vector(label = label[6:7])
lab2_net <- get_label_from_named_vector(label = label2[6:7])
fig1_draw <- ggdraw(fig1) +
  draw_label(lab_net, x = .25, y = .075, size = 11) +
  draw_line(
    x = c(0.01, 0.01, 0.49, .49),
    y = c(.11, 0.1, 0.1, .11),
    color = "black", size = 1
  ) + 
  draw_label(lab2_net, x = .75, y = .075, size = 11) +
  draw_line(
    x = c(0.52, 0.52, 0.98, .98),
    y = c(.11, 0.1, 0.1, .11),
    color = "black", size = 1
  )

test <- ggdraw(fig1)
for(i in seq(0,1, .02)) {
  test <- test +
  draw_line(x = c(0, 1), y = c(i , i), color = "black", size = .5) +
  draw_line(x = c(i, i), y = c(0 , 1), color = "black", size = .5)
}
for(i in seq(0,1, .1)) {
  test <- test +
  draw_line(x = c(0, 1), y = c(i , i), color = "red", size = 1) +
  draw_line(x = c(i, i), y = c(0 , 1), color = "red", size = 1)
}

fig1_draw_test <- fig1_draw +
  draw_line(
    x = c(0.1, 0.16),
    y = c(0.26, 0.325),
    color = "black", size = 1
  ) +
  draw_line(
    x = c(0.26, 0.24),
    y = c(0.26, 0.325),
    color = "black", size = 1
  ) +
  draw_line(
    x = c(0.43, 0.34),
    y = c(0.26, 0.325),
    color = "black", size = 1
  ) +
  draw_line(
    x = c(0.59, 0.69),
    y = c(0.26, 0.325),
    color = "black", size = 1
  ) +
  draw_line(
    x = c(0.76, 0.77),
    y = c(0.26, 0.325),
    color = "black", size = 1
  ) +
  draw_line(
    x = c(0.93, 0.89),
    y = c(0.26, 0.325),
    color = "black", size = 1
  )

save_plot(mypath("manuscript", "bef_stability", "figs/fig1.pdf"), fig1_draw_test,
nrow = 3, 
  ncol = 1,
  base_height = 4,
  base_width = 10 
)
```

