#' Get species from nodes
#' @param list 
#'
#' @details By convention the node naming scheme is set as the following:
#'  species_code + _ + class_nb. This function is just a wrapper around
#'  extract_all().
#'
get_species <- function(node_list) {

  species_resource_list <- stringr::str_extract_all(
    node_list, "[A-Za-z]+", simplify = TRUE)

  species_resource_list

}

#' Colours species 
#'
#'  
#' @inheritParams set_layout_graph a object generated by build_metaweb
#'
#' @return a colour scale 
set_color_species <- function (glay = NULL, net = NULL) {
  # A colour by species
  if (!is.null(glay)) {
    node_list <- glay$name
    species_resource_list <- stringr::str_extract_all(
      node_list, "[A-Za-z]+", simplify = TRUE) %>%
    as.vector %>% unique
  } else {
    stopifnot(!is.null(net))
    species_resource_list <- c(net[["from"]], net[["to"]]) %>% unique
  }

  # get hue color
  gg_color_hue <- function(n) {
    hues = seq(0, 360, length = n + 1)
    hcl(h = hues, l = 65, c = 100)[1:n]
  }
  species_color <- gg_color_hue(length(species_resource_list))
  names(species_color) <- species_resource_list

  species_color
}

#' Temporal graph for a station
#'
#' @param net data.frame contaning year variable and network list
#' @param meta an object created by build_metaweb
#' @param dead character vector indicating which node are basal
#' @param ... Other arguments to pass to set_layout_graph
#' @return a tibble containing a list of graph in a net_graph column
#' @seealso set_layout_graph
#' 
plot_temporal_network <- function(net, meta = NULL, dead = NULL, lay = NULL, ...){

  ## Color -------------------------
  color_scale <- set_color_species(net = net, glay = lay)
  ## Graph -------------------------
  net_graph <- graph_from_data_frame(net, directed = TRUE)
  net_graph <- select(net_ex, from, to, year) %>%
    arrange(year) %>%
    group_by(year) %>%
    nest() %>%
    mutate(net_graph = pmap(list(net = data, title = year),
    set_layout_graph, glay = lay, color_scale = color_scale))
  ## Get legend
  if (!is.null(lay)) {
    species_colour_legend <- get_legend(
      net_graph[1, ]$net_graph[[1]] +
    scale_color_manual(values = color_scale, limits = names(color_scale)) +
    labs(colour = "Species") +
    guides(colour = guide_legend(ncol = 3, byrow = TRUE))
    )
  } else {
    species_colour_legend <- get_legend(
      net_graph[1, ]$net_graph[[1]] +
    labs(colour = "Species") +
    guides(color = guide_legend(ncol = 2, byrow = TRUE))
    )
  }
  ## Remove legend in the other plots
  net_graph %<>%
    mutate(
      net_graph = map(net_graph, function (x) {
    x + theme(legend.position = "none",
      plot.margin = unit(c(0, 0, 0, 0), "cm"))
    })
    )
  plot_grid(plotlist = net_graph$net_graph,
    species_colour_legend)
}

#' Generate ggraph with a common layout
#'
#'  
#' @param net: data.frame describing edges 
#' @param glay a layout objet created by create_layout
#' @param title chr
#'
#' @return a ggraph object
set_layout_graph <- function (net = NULL, glay = NULL, x = NULL, y = NULL, title = NULL, biomass = NULL, color_scale= NULL) {

  net <- graph_from_data_frame(net)

  if (is.null(glay)) {
    # for species network:
    llay <- create_layout(net, layout = "kk")
    node_pos <- TrophInd(as_adjacency_matrix(net, sparse = FALSE), Dead = dead_material)$TL - 1
    llay$y <- node_pos
    llay$species <- get_species(llay$name)
  } else {
    # get node coord from the general:
    node_names <- attr(V(net), "name")
    coord <- filter(glay, name %in% node_names) %>%
      mutate(name = as.character(name))
    # local layout:
    llay <- create_layout(net, layout = "kk")
    saved_graph <- attr(llay, "graph")
    saved_circular_attr <- attr(llay, "circular")
    saved_class <- class(llay)
    llay <- select(llay, -x, -y) %>%
      mutate(name = as.character(name)) %>%
      left_join(., coord, by = "name") %>%
      select(x, y, everything())
    attr(llay, "graph") <- saved_graph
    attr(llay, "circular") <- saved_circular_attr
    class(llay) <- saved_class
  }

  if (!is.null(y)) {
    llay$y <- y
  }
  if (!is.null(x)) {
    llay$x <- x
  }

  p <- ggraph(llay) +
    geom_edge_fan(aes(alpha = ..index..), show.legend = FALSE) +
    geom_node_point()

  if (!is.null(title)) {
    p <- p + labs(title = title)
  }
  p <- p + theme_graph(
    foreground     = "steelblue",
    fg_text_colour = "white",
    base_family    = "sans",
    background     = NA
  )
  if (!is.null(color_scale)) {
    p <- p +
      scale_color_manual(values = color_scale) +
      geom_node_point(aes(color = species))
  }
  p
}

#' Personal plot theme
#'
#' @details This theme was design from the theme developped in the hrbrthemes
#' package: https://github.com/hrbrmstr/hrbrthemes 
#' @return a ggplot theme
theme_alain <- function(){

  hrbrthemes::theme_ipsum_rc() +
  theme(#Whipe
    text = element_text(family = "Helvetica", hjust = .5),
    axis.title = element_text(family = "Helvetica", hjust = .5, face = "bold", size = 10),
    plot.title = NULL,
    axis.title.x = NULL,
    axis.title.y = NULL,
    axis.text.x = NULL,
    axis.text.y = NULL,
    strip.text = NULL) +
  theme(#Set up
    plot.title = element_text(family = "Helvetica", hjust = .5, face = "bold", size = 10),
    axis.title.y = element_text(angle = 90, face = "bold"),
    axis.title.x = element_text(face = "bold"),
    axis.text = element_text(size = 8),
    strip.text = element_text(size = 8),
    plot.margin = unit(c(.5, .5, .5, .5), "cm")
    )
}
xylabs <- function (...) {
  dots <- pryr::named_dots(...)
  dots <- map(dots, eval) %>% unlist

  lab_list <- list(
    del = expression(bold(paste("Fraction of global dispersal (", delta, ")"))),
    biomass_cv = paste("CV of biomass"),
    biomass_stab = paste("Stability of Biomass"),
    biomass_avg = paste("Average biomass (g)"),
    network_med = paste("Median of network metrics"),
    nbnode = paste("Number of nodes"),
    richness = paste("Species richness"),
    richness_cv = paste("CV of richness"),
    richness_avg = paste("Average richness"),
    richness_avg = paste("Median richness"),
    connectance = paste("Connectance"),
    connectance_avg = paste("Average connectance"),
    connectance_med = paste("Median connectance"),
    connectance_cv = paste("CV of connectance"),
    diversity = paste("Diversity")
    )
  
  lab_used <- lab_list[dots]
  names(lab_used) <- names(dots)

  labs(
    x = lab_used["x"][[1]],
    y = lab_used["y"][[1]]
    )
}

###############
#  Labellers  #
###############

mylabel <- function() {
  ggplot2::as_labeller(c(
    connectance = "Connectance",
    richness = "Number of nodes",
    max_troph_level = "Highest trophic level",
    mean_troph_level = "Average trophic level",
    modularity = "Modularity",
    nestedness = "Nestedness",
    nbnode = "Number of nodes",
    richness_cv = "CV",
    richness_avg = "Average",
    richness_med = "Median richness",
    betadiv = "Beta-diversity"
    #betadiv = expression(bold(paste(beta, "-diversity", sep = "")))
    #see https://stackoverflow.com/questions/35524202/as-labeller-with-expression-in-ggplot2-facet-wrap?rq=1
      )
    )
}

#' Troph group labeller
#' Returns a labeller for ggplot2
#' @param troph_class a object created by get_size_class function
#' @return a labeller for ggplot2
troph_group_labeller <- function (troph_class = NULL, round_lvl = 2) {

  if (is.null(troph_class)) {
    data(trophic_class)
    troph_class <- trophic_class
  }
  troph_class %<>%
    dplyr::mutate(
      lower = paste("[", round(lower, round_lvl), sep = ""),
      upper = paste(round(upper, round_lvl), "]", sep = "")
      ) %>%
  tidyr::unite(bounds, lower, upper, sep = ";") %>%
  dplyr::rename(troph_group = class_id)

  bounds <- troph_class$bounds
  names(bounds) <- troph_class$troph_group
  as_labeller(bounds)

}
