#' Get species from nodes
#' @param list 
#'
#' @details By convention the node naming scheme is set as the following:
#'  species_code + _ + class_nb. This function is just a wrapper around
#'  extract_all().
#'
get_species <- function(node_list) {

  species_resource_list <- stringr::str_extract_all(
    node_list, "[A-Za-z]+", simplify = TRUE)

  species_resource_list

}

#' Colours species 
#'
#'  
#' @inheritParams set_layout_graph a object generated by build_metaweb
#'
#' @return a colour scale 
set_color_species <- function (sp_list = NULL, glay = NULL, net = NULL) {
  # A colour by species
  if (!is.null(sp_list)) {
    species_resource_list <- sp_list 
  } else if (!is.null(glay)) {
    node_list <- glay$name
    species_resource_list <- stringr::str_extract_all(
      node_list, "[A-Za-z]+", simplify = TRUE) %>%
    as.vector %>% unique
  } else {
    stopifnot(!is.null(net))
    species_resource_list <- c(net[["from"]], net[["to"]]) %>% unique
  }

  # get hue color
  gg_color_hue <- function(n) {
    hues = seq(0, 360, length = n + 1)
    hcl(h = hues, l = 65, c = 100)[1:n]
  }
  species_color <- gg_color_hue(length(species_resource_list))
  names(species_color) <- species_resource_list

  species_color
}

#' Temporal graph for a station
#'
#' @param net data.frame contaning date variable and network list
#' @param meta an object created by build_metaweb
#' @param dead character vector indicating which node are basal
#' @param x named vector of node x position
#' @param y list of named vector of node vertical position
#' @param ... optional parameters for set_layout_graph  
#' @return a plot_grid object 
#' @seealso set_layout_graph
#' 
plot_temporal_network <- function(data = NULL, net_var = NULL, date = NULL, y = NULL, x = NULL, size = NULL, color = NULL, ...){
  net_var <- rlang::enquo(net_var)
  net_var_chr <- rlang::quo_name(net_var)

  if (is.null(color)) {
  # Get species_resource list
  species_resource_list <- purrr::map(net_test$net, function(net) {
    if (class(net) == "data.frame") {
      net <- graph_from_data_frame(net, directed = TRUE)
    } else if (class(net) == "matrix") {
      net <- graph_from_adjacency_matrix(net, mode = "directed")
    } else {
      stopifnot(class(net) == "igraph")
    }
    attr(V(net), "name")
      }) %>%
  unlist(., use.names = FALSE) %>%
  unique
  color <- set_color_species(species_resource_list)
  }

  data %<>%
    dplyr::arrange(date) %>%
    dplyr::mutate(!!net_var := purrr::pmap(
	list(
	  net = !!net_var,
	  y = y,
	  title = date,
	  biomass = size),
	~set_layout_graph(
	  net = ..1,
	  y = ..2,
	  title = ..3,
	  biomass = ..4,
	  x = x,
	  color_scale = color
	  )
	))

    species_colour_legend <- cowplot::get_legend(
      data[[net_var_chr]][[1]] +
	scale_color_manual(values = color, limits = names(color)) +
	labs(colour = "Species") +
	guides(colour = guide_legend(ncol = 3, byrow = TRUE))
      )

  ## Remove legend in the other plots
  data %<>%
    mutate(
      !!net_var := map(!!net_var, function (x) {
    x + theme(legend.position = "none",
      plot.margin = unit(c(0, 0, 0, 0), "cm"))
    })
    )
  p <- cowplot::plot_grid(plotlist = data[[net_var_chr]])
  cowplot::plot_grid(p, species_colour_legend, nrow = 2, rel_widths = c(1, 0.2))
}

#' Generate ggraph with a common layout
#'
#'  
#' @param net: data.frame describing edges 
#' @param glay a layout objet created by create_layout
#' @param title chr
#'
#' @return a ggraph object
set_layout_graph <- function (net = NULL, glay = NULL, x = NULL, y = NULL, title = NULL, biomass = NULL, color_scale= NULL, dead_material = NULL) {


  if (class(net) == "data.frame") {
    net <- graph_from_data_frame(net, directed = TRUE)
  } else if (class(net) == "matrix") {
    net <- graph_from_adjacency_matrix(net, mode = "directed")
  } else {
    stopifnot(class(net) == "igraph")
  }

  if (is.null(glay)) {
    # for species network:
    llay <- ggraph::create_layout(net, layout = "kk")
    node_pos <- NetIndices::TrophInd(as_adjacency_matrix(net, sparse = FALSE), Dead = dead_material)$TL - 1
    llay$y <- node_pos
    llay$species <- get_species(llay$name)
  } else {
    # get node coord from the general:
    node_names <- attr(V(net), "name")
    coord <- filter(glay, name %in% node_names) %>%
      mutate(name = as.character(name))
    # local layout:
    llay <- ggraph::create_layout(net, layout = "kk")
    saved_graph <- attr(llay, "graph")
    saved_circular_attr <- attr(llay, "circular")
    saved_class <- class(llay)
    llay <- select(llay, -x, -y) %>%
      mutate(name = as.character(name)) %>%
      left_join(., coord, by = "name") %>%
      select(x, y, everything())
    attr(llay, "graph") <- saved_graph
    attr(llay, "circular") <- saved_circular_attr
    class(llay) <- saved_class
  }

  if (!is.null(y)) {
    stopifnot(all(names(y) %in% llay$name))
    llay$y <- y[llay$name]
  }
  if (!is.null(x)) {
    stopifnot(all(names(x) %in% llay$name))
    llay$x <- x[llay$name]
  }
  p <- ggraph::ggraph(llay) +
    ggraph::geom_edge_fan(aes(alpha = ..index..), show.legend = FALSE)
  if (is.null(biomass)) {
    p <- p +
      ggraph::geom_node_point()
  } else {
    stopifnot(all(names(biomass) %in% llay$name))
    dataset <- p$data
    dataset$biomass <- biomass[llay$name]
    p <- p +
      ggraph::geom_node_point(data = dataset,
	aes(x = x, y = y, size = biomass, color = species)) +
      scale_color_manual(values = color_scale, limits = names(color_scale))
  }


  if (!is.null(title)) {
    p <- p + labs(title = title)
  }
  p <- p + ggraph::theme_graph(
    foreground     = "steelblue",
    fg_text_colour = "white",
    base_family    = "sans",
    background     = NA
  )
  if (!is.null(color_scale)) {
    p <- p
      #ggraph::geom_node_point(aes(color = species, size = biomass)) +
  }
  p

}

#' Personal plot theme
#'
#' @details This theme was design from the theme developped in the hrbrthemes
#' package: https://github.com/hrbrmstr/hrbrthemes 
#' @return a ggplot theme
theme_alain <- function(){

  hrbrthemes::theme_ipsum_rc() +
  theme(#Whipe
    text = element_text(family = "Helvetica", hjust = .5),
    axis.title = element_text(family = "Helvetica", hjust = .5, face = "bold", size = 10),
    plot.title = NULL,
    axis.title.x = NULL,
    axis.title.y = NULL,
    axis.text.x = NULL,
    axis.text.y = NULL,
    strip.text = NULL) +
  theme(#Set up
    plot.title = element_text(family = "Helvetica", hjust = .5, face = "bold", size = 10),
    axis.title.y = element_text(angle = 90, face = "bold"),
    axis.title.x = element_text(face = "bold"),
    axis.text = element_text(size = 8),
    strip.text = element_text(size = 8),
    plot.margin = unit(c(.5, .5, .5, .5), "cm")
    )
}
xylabs <- function (...) {
  dots <- pryr::named_dots(...)
  dots <- map(dots, eval) %>% unlist

  lab_list <- list(
    del = expression(bold(paste("Fraction of global dispersal (", delta, ")"))),
    biomass_cv = paste("CV of biomass"),
    biomass_stab = paste("Stability of Biomass"),
    biomass_avg = paste("Average biomass (g)"),
    network_med = paste("Median of network metrics"),
    nbnode = paste("Number of nodes"),
    richness = paste("Species richness"),
    richness_cv = paste("CV of richness"),
    richness_avg = paste("Average richness"),
    richness_avg = paste("Median richness"),
    connectance = paste("Connectance"),
    connectance_avg = paste("Average connectance"),
    connectance_med = paste("Median connectance"),
    connectance_cv = paste("CV of connectance"),
    diversity = paste("Diversity")
    )
  
  lab_used <- lab_list[dots]
  names(lab_used) <- names(dots)

  labs(
    x = lab_used["x"][[1]],
    y = lab_used["y"][[1]]
    )
}

###############
#  Labellers  #
###############

mylabel <- function() {
  ggplot2::as_labeller(c(
    connectance = "Connectance",
    richness = "Number of nodes",
    max_troph_level = "Highest trophic level",
    mean_troph_level = "Average trophic level",
    modularity = "Modularity",
    nestedness = "Nestedness",
    nbnode = "Number of nodes",
    richness_cv = "richness CV",
    richness_avg = "Average richness",
    richness_med = "Median richness",
    betadiv = "Beta-diversity"
    #betadiv = expression(bold(paste(beta, "-diversity", sep = "")))
    #see https://stackoverflow.com/questions/35524202/as-labeller-with-expression-in-ggplot2-facet-wrap?rq=1
      )
    )
}

#' Troph group labeller
#' Returns a labeller for ggplot2
#' @param troph_class a object created by get_size_class function
#' @return a labeller for ggplot2
troph_group_labeller <- function (troph_class = NULL, round_lvl = 2) {

  if (is.null(troph_class)) {
    data(trophic_class)
    troph_class <- trophic_class
  }
  troph_class %<>%
    dplyr::mutate(
      lower = paste("[", round(lower, round_lvl), sep = ""),
      upper = paste(round(upper, round_lvl), "]", sep = "")
      ) %>%
  tidyr::unite(bounds, lower, upper, sep = ";") %>%
  dplyr::rename(troph_group = class_id)

  bounds <- troph_class$bounds
  names(bounds) <- troph_class$troph_group
  as_labeller(bounds)

}
